======================================================================
ERROR: test_mail (test_mail.TestMail)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_mail.py", line 46, in test_mail
    raise ValueError("user or pwd is not specified.")
ValueError: user or pwd is not specified.

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
